# clang-tidy integration

function(enable_clang_tidy target_name)
    if(NOT DEVDASH_ENABLE_CLANG_TIDY)
        return()
    endif()

    find_program(CLANG_TIDY clang-tidy)
    if(CLANG_TIDY)
        set_target_properties(${target_name} PROPERTIES
            CXX_CLANG_TIDY "${CLANG_TIDY}"
        )

        # Exclude Qt-generated files from clang-tidy analysis
        # These are auto-generated by Qt build tools and we can't control their content
        get_target_property(TARGET_SOURCES ${target_name} SOURCES)
        if(TARGET_SOURCES)
            foreach(source ${TARGET_SOURCES})
                # Skip files in .rcc/, moc_*, *_autogen/, qmlcache directories
                if(source MATCHES "(\\.rcc/|/moc_|_autogen/|qmlcache)")
                    set_source_files_properties(${source} PROPERTIES
                        CXX_CLANG_TIDY ""
                    )
                endif()
            endforeach()
        endif()
    else()
        message(WARNING "clang-tidy not found, static analysis disabled")
    endif()
endfunction()
